version: "2"

services:
  backend:
    container_name: modi-node-server
    build: ./backend/
    command: npm run dev
    ports:
      - "5000:5000"
    restart: always
  frontend:
    container_name: modi-react-client
    build: ./frontend/
    ports:
      - "3000:3000"
    restart: always
